### ISSUE TITLE
Need to remove Readability API support

### ISSUE THREAD

**Issue by churchs19** [Muffo/fullyfeedly#35]
Readability is shutting down its API on December 10th, 2016. We need to remove the Readability API support prior to that to avoid a broken user experience. We probably need a migration plan/dialog to help users move to a new parser if they are using Readability.

![image](https://cloud.githubusercontent.com/assets/1831494/20357788/f48f376c-abee-11e6-9a99-8443889fd0e2.png)

**Comment by Muffo** [comment]
I received the email today as well!

Here is my proposal:

* If the user already uses Mercury there's no need to show a notification
* If the user uses Readability then every time the extension is used to show an article we prepend a *warning message* to the content
* The *warning message* informs the user that the API will be deprecated soon and invite him to change to Mercury. It also contains a link to the setting page of the extension (it should be possible...)
* In the setting page we display a similar *warning message* when the user has the Readability API selected.

On the 10th of December we replace the extension with a new version where Readability has completely been removed.
Ideally, if the user hasn't switched we should change the setting automatically to use a different API. Probably it should be the Boilerpipe since it does not require any Key.

Would that work in your opinion?

I am happy to hear your suggestion :)

**Comment by churchs19** [comment]
That sounds good to me.

**Comment by Muffo** [comment]
Great! I am working on it now 👍

**Comment by Muffo** [comment]
The following message is now displayed to users that haven't migrated to Mercury yet:

<img width="671" alt="schermata 2016-11-19 alle 12 56 48" src="https://cloud.githubusercontent.com/assets/538925/20455613/df24c7c8-ae57-11e6-93a2-842ac8d9115d.png">

@churchs19 could you please let me know if it's working OK?
