### ISSUE TITLE
it's....... not working?

### ISSUE THREAD

**Issue by spookyliz** [Muffo/fullyfeedly#53]
i have no more succinct way to put it, the extension is just not working, no "show full article" feature in any of my feeds. i stopped and restarted the extension, removed it and re-added it, fiddled with what few options there were to fiddle with--nothing.

**Comment by Muffo** [comment]
Thanks for reporting the issue! It was also flagged by other users and I will try to take a look. It's likely the format of the Feedly website has changed and the extension cannot add the button anymore.

**Comment by spookyliz** [comment]
sweet, thank you. and thank you for creating the extension in the first place, it's such a simple thing but makes life so much easier.

**Comment by Muffo** [comment]
Preparing a new release now. Fix will be in version 0.11.1

**Comment by Trit34** [comment]
@Muffo If you’re still here, it’s not working again since yesterday. Could you fix it, please?

**Comment by Muffo** [comment]
Thanks @Trit34 for reporting the bug. Unfortunately I have very limited time to work on this extension. Is it still broken?

**Comment by Trit34** [comment]
@Muffo Hi! Yes, it is still broken since there is no “Show full article” button anymore (and the `f f` keyboard shortcut does not work either). Feedly made some changes and it has first resulted in moving (and reducing the size) of the SFA button, and now, there is only the “Visit Website” button available (but if we use RSS, it is to avoid having to go to the sites, isn’t it?).
